[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/assets/*.mjs"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
